//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthUsingIdentity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseDtl()
        {
            this.Admissions = new HashSet<Admission>();
            this.ModuleDtls = new HashSet<ModuleDtl>();
            this.ResultMakes = new HashSet<ResultMake>();
        }
        [Display(Name = "Course Id")]
        public int CourseDtlId { get; set; }
        [Display(Name = "Name")]
        //[Required(ErrorMessage = "Course Required")]
        public string CrsName { get; set; }
        [Display(Name = "Duration")]
        //[Required(ErrorMessage = "Duration Required")]
        public int CrsDuratin { get; set; }
        [Display(Name ="Shift")]
        //[Required(ErrorMessage = "Shift Required")]
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        [Display(Name ="Fees")]
        //[Required(ErrorMessage = "Fees Required")]
        public decimal CrsFee { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleDtl> ModuleDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultMake> ResultMakes { get; set; }
    }
}
