//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthUsingIdentity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ModuleDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleDtl()
        {
            this.Admissions = new HashSet<Admission>();
            this.ResultMakes = new HashSet<ResultMake>();
        }
        [Display(Name ="Module Id")]
        public int ModuleDtlId { get; set; }
        [Display(Name ="Course Id")]
        //[Required(ErrorMessage = "Course Required")]
        public int CourseDtlId { get; set; }
        [Display(Name ="Module Name")]
        //[Required(ErrorMessage = "Module Required")]
        public string MdlName { get; set; }
        [Display(Name ="Fees")]
        //[Required(ErrorMessage = "Fees Required")]
        public decimal MdlFees { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        public virtual CourseDtl CourseDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultMake> ResultMakes { get; set; }
    }
}
