//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthUsingIdentity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInformation()
        {
            this.Admissions = new HashSet<Admission>();
            this.ResultMakes = new HashSet<ResultMake>();
        }
        [Key]
        [Display(Name = "Student Id")]
        public int StudentId { get; set; }
        [Display(Name = "Name")]
        public string StName { get; set; }
        [Display(Name = "Mobile No")]
        public string Phone { get; set; }
        [Display(Name = "Date of birth")]
        public string DateOfbirth { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Address")]
        public string Addresss { get; set; }
        [Display(Name ="Image")]
        public string ImageName { get; set; }
        [Display (Name ="Emg Contact No")]
        public string ImageData { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultMake> ResultMakes { get; set; }
    }
}
