//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthUsingIdentity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TspInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TspInfo()
        {
            this.Admissions = new HashSet<Admission>();
        }
         [Display (Name ="TSP Id")]
        public int ID { get; set; }
        [Display(Name = "Name")]
        //[Required(ErrorMessage = "TSP Name Required")]
        public string TspName { get; set; }
        [Display(Name = "Mobile No")]
        //[Required(ErrorMessage = "Mobile No Required")]
        public string TspPhone { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        //[Required(ErrorMessage = "Email Address Required")]
        public string TspEmail { get; set; }
        [Display(Name = "Address")]
        public string TspAddress { get; set; }
        [Display(Name = "Establish Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime SrtDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
    }
}
